### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by mag002** [ThuyKat/front-end-bootcamp#1]
Should not use a fixed unit
https://github.com/ThuyKat/front-end-bootcamp/blob/0d11af9ddc3ac562f60d01a792716e8f254f77a5/resume.css#L20

**Comment by mag002** [comment]
can use the prettier to format the document (HTML, CSS files)

**Comment by ThuyKat** [comment]
> Should not use a fixed unit
> 
> https://github.com/ThuyKat/front-end-bootcamp/blob/0d11af9ddc3ac562f60d01a792716e8f254f77a5/resume.css#L2
I have changed position to sticky

**Comment by ThuyKat** [comment]
> can use the prettier to format the document (HTML, CSS files)

the format has been fixed too.
